name: Build Godot Project

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  export_web:
    name: Export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.3/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.3/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./game/
          cache: true
          archive_output: true
          use_preset_export_path: true
          export_debug: false

      - name: Upload web build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./build/web/web.zip
          itchUsername: ${{ secrets.ITCHIO_USERNAME }}
          itchGameId: ${{ secrets.ITCHIO_GAME }}
          buildChannel: html5

      - name: Upload windows build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./build//win/win.zip
          itchUsername: ${{ secrets.ITCHIO_USERNAME }}
          itchGameId: ${{ secrets.ITCHIO_GAME }}
          buildChannel: windows
