name: itch.io upload

# define what triggers the action
on: push

# the directory where your game is
env:
  WORKING_DIRECTORY: .
  GODOT_VERSION: '4.1.3'

jobs:
  deploy:
    # only run action, if pushed on master branch
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Create export directory
        run: mkdir -p ./build/web
        
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Cache Godot files
        id: cache-godot
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/**
            /usr/local/bin/godot
            ~/.config/godot/**
          key: ${{ runner.os }}-godot-${GODOT_VERSION}
        
      - name: Setup Headless Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        shell: bash
        run: |
          wget -q https://downloads.tuxfamily.org/godotengine/${{ GODOT_VERSION }}/Godot_v${{ GODOT_VERSION }}-stable_linux.x86_64.zip
          wget -q https://downloads.tuxfamily.org/godotengine/${{ GODOT_VERSION }}/Godot_v${{ GODOT_VERSION }}-stable_export_templates.tpz
          mkdir ~/.cache
          mkdir -p ~/.config/godot
          mkdir -p ~/.local/share/godot/templates/${{ GODOT_VERSION }}.stable
          unzip Godot_v${{ GODOT_VERSION }}-stable_linux.x86_64.zip
          mv Godot_v${{ GODOT_VERSION }}-stable_linux_headless.64 /usr/local/bin/godot
          unzip Godot_v${{ GODOT_VERSION }}-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/templates/${{ GODOT_VERSION }}.stable
          rm -f Godot_v${{ GODOT_VERSION }}-stable_linux.x86_64.zip Godot_v${{ GODOT_VERSION }}-stable_export_templates.tpz
          godot -e -q

      - name: Export
        shell: bash
        run: godot --headless --path ${{ WORKING_DIRECTORY }} --export-release Web ./build/web/index.html

      # uploads to itch.io
      # more info here https://github.com/dulvui/itchio-butler-upload
      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: build/web
          api-key: ${{ secrets.BUTLER_API_KEY }}
          user: ${{ secrets.ITCHIO_USERNAME }}
          game: ${{ secrets.ITCHIO_GAME }}
          channel: html5
